Adding sample code for CORS
pantheon-systems/documentation pull request #6029
Opened 2020-10-04 02:07 UTC by carl-alberto

Closes: #6028

## Summary

Adding sample code for CORS because the existing seems not to be working anymore

## Effect
Adding sample code for CORS because the existing seems not to be working anymore

## Remaining Work

The following changes still need to be completed:

- [ ] update relevant section here https://pantheon.io/docs/platform-considerations
- [ ] add sample code here https://pantheon.io/docs/mu-plugin#example-code-snippets

## Post Launch

**Do not remove** - To be completed by the docs team upon merge:

- [ ] Redirect `/docs/old-path/` => `/docs/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] For Heroes - add a props post to the [discussion board](https://discuss.pantheon.io/c/pantheon-platform/documentation/17).

2020-10-04 02:13 UTC, pantheondocs commented
Lighthouse Audit Results:

| Description | [Live](https://pantheon.io/docs) | [pr-6029](https://pr-6029--pantheon-docs.my.pantheonfrontend.website/docs) | Difference |
| --- | --- | --- | --- |
| Performance Score | `66` | `67` | `1` |
| Best Practice Score | `86` | `86` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `88` | `88` | `0` |

Lighthouse Audit Reports:

- [`pr-6029` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/24009/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/24009/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)


[Preview Environment](https://pr-6029--pantheon-docs.my.pantheonfrontend.website/docs)

2020-10-15 02:50 UTC, carl-alberto commented
@alexfornuto May I also request this PR to be tagged as `hacktoberfest-accepted` please? :)

2020-10-16 15:14 UTC, alexfornuto requested changes
Thanks @carl-alberto! This looks good, I only have the one question remaining.

2020-10-16 15:14 UTC, alexfornuto commented on source/content/mu-plugin.md
> +    $headers['Access-Control-Allow-Origin'] = 'https://example.com';
@carl-alberto if the user wanted to enable CORS for an multiple domains, as demo'd in the old example with the array `$urls[]`, how would they do it here? Does the right side of the `=` become an array, or is this line repeated for each domain?

2020-10-18 02:38 UTC, carl-alberto commented on source/content/mu-plugin.md
> +    $headers['Access-Control-Allow-Origin'] = 'https://example.com';
It seems as per the specification of that header, it is only allowed one domain or wildcard (*), we can put that into a note or they need to have a code that detects the incoming domain request to check if that domain is allowed like one of the suggested answers here https://stackoverflow.com/questions/1653308/access-control-allow-origin-multiple-origin-domains

2020-10-19 14:08 UTC, alexfornuto commented on source/content/mu-plugin.md
> +    $headers['Access-Control-Allow-Origin'] = 'https://example.com';
@carl-alberto can you make that clarification in this PR? I'm afraid I don't understand the application well enough to attempt it.

2020-12-03 07:04 UTC, carl-alberto commented on source/content/mu-plugin.md
> +    $headers['Access-Control-Allow-Origin'] = 'https://example.com';
Tried to create a sample code to demonstrate the solution that they provided in here https://stackoverflow.com/questions/1653308/access-control-allow-origin-multiple-origin-domains but not sure why I was not able to reliably pull off the $_SERVER[ 'HTTP_ORIGIN' ] variable for external requests

Maybe we can go through with that PR as it works for 1 domain and wildcard domain(*), then we can later on add an additional code where it can work with multiple domains @alexfornuto

2020-12-07 22:32 UTC, alexfornuto commented on source/content/mu-plugin.md
> +    $headers['Access-Control-Allow-Origin'] = 'https://example.com';
Sounds like a worthwhile next step. Lemme just get someone from engineering to weigh in on this. Maybe @ari-gold?

2020-12-08 18:06 UTC, alexfornuto commented on source/content/mu-plugin.md
> +    $headers['Access-Control-Allow-Origin'] = 'https://example.com';
Tagging @tmountjr and @nullvariable to weigh in.

2020-12-09 19:47 UTC, nullvariable commented on source/content/mu-plugin.md
> +    $headers['Access-Control-Allow-Origin'] = 'https://example.com';
HTTP_HOST is generally what you'd go for here if you needed it to be dynamic. Pseudo code:
if ( isset $_SERVER[HTTP_HOST] ) {
  headers[header] = "https://" . HTTP_HOST;
}
or you could use a switch statement against the host value as well. Host won't be defined during cli calls, but that's not an issue here.

example of how we use host to set the wordpress site/home urls: https://github.com/pantheon-systems/WordPress/blob/default/wp-config-pantheon.php#L62

2020-12-09 19:49 UTC, nullvariable commented on source/content/mu-plugin.md
> +    $headers['Access-Control-Allow-Origin'] = 'https://example.com';
docs for the spec https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin

> <origin>
> Specifies an origin. Only a single origin can be specified. If the server supports clients from multiple origins, it must return the origin for the specific client making the request.

so definitely need to do the dynamic approach if you need to support, for example the platform domain and a custom domain.

2021-01-02 06:21 UTC, carl-alberto commented on source/content/mu-plugin.md
> +    $headers['Access-Control-Allow-Origin'] = 'https://example.com';
Thanks for the tips @nullvariable but unfortunately did not have any luck with it, but got this code working, just have to make sure cache is cleared so it would work out properly:

```
function dynamic_cors_headers( $headers ) {
	if ( ! is_admin() ) {
		 $allowed_domains = array( 
		 	'https://dev-cors-request-1.pantheonsite.io' , 
		 	'http://example.com', 
		 	'https://allowed-cors-request-1.pantheonsite.io'
		 );
    	 if ( in_array( $_SERVER[ 'HTTP_ORIGIN' ] , $allowed_domains ) ) {
		 	$url = $_SERVER[ 'HTTP_ORIGIN' ];
		 	$headers['Access-Control-Allow-Origin'] = $url;
		 	return $headers;
		 } else {
		 	return null;
		}
	}
}
add_filter( 'wp_headers', 'dynamic_cors_headers' );
```

I have a POC site that we can play with @alexfornuto

2021-01-05 23:15 UTC, alexfornuto commented on source/content/mu-plugin.md
> +    $headers['Access-Control-Allow-Origin'] = 'https://example.com';
@nullvariable I'd appreciate if if you could provide any input on the code above.

2021-01-07 14:05 UTC, nullvariable commented on source/content/mu-plugin.md
> +    $headers['Access-Control-Allow-Origin'] = 'https://example.com';
I would probably drop the `! is_admin` condition since wp ajax requests go through the admin filter, and would be a common endpoint for requests that would need CORS, and the headers should be filtered, so that other plugins are not broken if they're adding anything. So I'd do something like:

```
function dynamic_cors_headers( $headers ) {
  $allowed_domains = array( 
    'https://dev-exampleallowedurl.pantheonsite.io' , 
    'http://example.com', 
  );
  if ( in_array( $_SERVER[ 'HTTP_ORIGIN' ] , $allowed_domains ) ) {
    $url = $_SERVER[ 'HTTP_ORIGIN' ];
    $headers['Access-Control-Allow-Origin'] = $url;
  }
  return $headers;
}
add_filter( 'wp_headers', 'dynamic_cors_headers' );
```

2021-07-06 14:41 UTC, carolyn-shannon commented
Reached out to @carl-alberto for assistance.

2022-02-04 20:59 UTC, joa-pan commented
@carl-alberto is any work remaining on this PR? Has the conversation been resolved?

2022-02-05 11:34 UTC, carl-alberto commented
@joa-pan , sorry was not able to go back into this issue in the past year as we were not able to conclude a solution with Doug and Alex :( unfortunately, not sure if I'll have more time to get back into this again soon

2022-03-10 16:00 UTC, joa-pan commented
Thanks @carl-alberto. Your work on this was tremendous and so incredibly helpful. We really appreciated all your help. We'll hand it off to another SME for review. Thanks a million for everything 🎉

2022-03-10 22:34 UTC, jms-pantheon commented
Hey @joa-pan I've used the review comments here and some outside research to build a new snippet, tested on a deployed WordPress install and received the expected headers.

2022-03-11 06:21 UTC, joa-pan commented
@jms-pantheon you are incredible! Thank you so much 🎉

2022-03-11 06:27 UTC, joa-pan approved these changes
LGTM

2022-03-11 06:40 UTC, merged