Added New Issue for Autoptimize Plugin
pantheon-systems/documentation pull request #6123
Opened 2020-11-17 19:10 UTC by jahzlariosa

**Note:** Please fill out the PR Template to ensure proper processing.

Closes: #

## Summary

**[Doc Title](https://pantheon.io/docs/doc-title)** - Autoptimize new required file.

## Effect
Autoptimize will start throwing warnings about a new PHP file that seems to be required for the plugin to work properly, This file gets added upon plugin activation.

## Post Launch

**Do not remove** - To be completed by the docs team upon merge:

- [ ] Redirect `/docs/old-path/` => `/docs/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] For Heroes - add a props post to the [discussion board](https://discuss.pantheon.io/c/pantheon-platform/documentation/17).
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

2020-11-17 19:17 UTC, pantheondocs commented
Lighthouse Audit Results:

| Description | [Live](https://pantheon.io/docs) | [pr-6123](https://pr-6123--pantheon-docs.my.pantheonfrontend.website/docs) | Difference |
| --- | --- | --- | --- |
| Performance Score | `63` | `71` | `8` |
| Best Practice Score | `86` | `86` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `88` | `88` | `0` |

Lighthouse Audit Reports:

- [`pr-6123` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/24889/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/24889/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)


[Preview Environment](https://pr-6123--pantheon-docs.my.pantheonfrontend.website/docs)

2020-11-18 11:36 UTC, marfillaster commented
Related Issue [#6022](https://github.com/pantheon-systems/documentation/issues/6022)

2020-11-22 10:24 UTC, marfillaster requested changes

2020-11-22 10:24 UTC, marfillaster commented on source/content/plugins-known-issues.md
> +and enabling this setting requires write access and specific location directive not configured in platform's Nginx configuration.
```suggestion
and enabling this setting requires write access and a [location directive](https://wordpress.org/plugins/autoptimize/#%0Awhat%20does%20%E2%80%9Cenable%20404%20fallbacks%E2%80%9D%20do%3F%20why%20would%20i%20need%20this%3F%0A) not configured in platform's Nginx configuration. 
```

2020-11-22 10:24 UTC, marfillaster commented on source/content/plugins-known-issues.md
> +The Pantheon Platform does not provide support for custom configuration, Hence file redirects will not work. More information can be found in [here.](https://pantheon.io/docs/advanced-redirects#redir
```suggestion
The Pantheon Platform does not provide support for custom configuration, hence file redirects will not work. More information can be found in [here.](https://pantheon.io/docs/advanced-redirects#redirect-files)
```

2020-12-09 20:07 UTC, alexfornuto approved these changes
Thanks @jahzlariosa and @marfillaster!

2020-12-10 19:46 UTC, merged