Gatsby 2.27
pantheon-systems/documentation pull request #6146
Opened 2020-12-01 19:24 UTC by alexfornuto

## Summary

**Site Upgrade** - Upgrade to Gatsby 2.27. Note: the development server should be started with `npm run develop` to include the flags for experimental new features.

## Post Launch

- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

2020-12-01 22:36 UTC, alexfornuto commented
This needs an updated docker image from the orb providing Node >= 11, waiting on that.

2020-12-07 17:48 UTC, pantheondocs commented
Lighthouse Audit Results:

| Description | [Live](https://pantheon.io/docs) | [pr-6146](https://pr-6146--pantheon-docs.my.pantheonfrontend.website/docs) | Difference |
| --- | --- | --- | --- |
| Performance Score | `60` | `61` | `1` |
| Best Practice Score | `86` | `86` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `88` | `88` | `0` |

Lighthouse Audit Reports:

- [`pr-6146` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/25182/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/25182/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)


[Preview Environment](https://pr-6146--pantheon-docs.my.pantheonfrontend.website/docs)

2021-02-02 21:48 UTC, alexfornuto commented
Blocked by https://github.com/pantheon-systems/frontend-orb/pull/53, as we want to keep using versions from the default branch for the orb.

2021-06-09 17:56 UTC, georch requested changes
@alexfornuto The team published a new release to update to Node 12 https://github.com/pantheon-systems/frontend-orb/releases/tag/0.4.0 Please update the CircleCI accordingly. cc @carolyn-shannon

2021-06-09 17:56 UTC, georch commented on .circleci/config.yml
> +  pfe: pantheon-systems/front-end@dev:node-12
```suggestion
  pfe: pantheon-systems/front-end@0.4.0
```

2021-06-15 18:42 UTC, carolyn-shannon commented on .circleci/config.yml
> +  pfe: pantheon-systems/front-end@dev:node-12
Thanks, will do.

2021-06-30 03:16 UTC, jmolivas commented
This PR can be closed since the PR https://github.com/pantheon-systems/documentation/pull/6505 was merged cc: @carolyn-shannon @EdwardAngert

2021-06-30 15:02 UTC, carolyn-shannon commented
Duplicate of #6505

2021-06-30 15:02 UTC, closed without merging