April 2021 Changelog
pantheon-systems/documentation pull request #6343
Opened 2021-04-05 22:46 UTC by carolyn-shannon

Closes: #6311 

## Summary

**[Changelog April 2021](https://pantheon.io/docs/changelog)** - April 2021 Changelog

## Post Launch

**Do not remove** - To be completed by the docs team upon merge:

- [ ] Redirect `/docs/old-path/` => `/docs/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] For Heroes - add a props post to the [discussion board](https://discuss.pantheon.io/c/pantheon-platform/documentation/17).
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

2021-04-05 22:52 UTC, pantheondocs commented
Lighthouse Audit Results:

| Description | [Live](https://pantheon.io/docs) | [pr-6343](https://pr-6343--pantheon-docs.my.pantheonfrontend.website/docs) | Difference |
| --- | --- | --- | --- |
| Performance Score | `62` | `61` | `-1` |
| Best Practice Score | `79` | `79` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-6343` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/26824/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/26824/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)


[Preview Environment](https://pr-6343--pantheon-docs.my.pantheonfrontend.website/docs)

2021-04-07 13:57 UTC, EdwardAngert requested changes

2021-04-07 13:57 UTC, EdwardAngert commented on source/changelogs/2021-04-01-April.md
> +Convert your Pantheon-hosted Drupal 8 sites to Drupal 9 with Integrated Composer, using the [Drupal 8 to 9 Conversion Guide](/drupal-9#convert-an-existing-drupal-8-site-to-drupal-9). [Integrated Comp
The Platform team had planned for this to be true by the time we published this, but as it stands, this heading in the D9 doc this links to doesn't exist. Can we link to the [guide instead](https://pantheon.io/docs/guides/drupal-9-migration)?

2021-04-07 14:51 UTC, EdwardAngert approved these changes

2021-04-07 14:51 UTC, merged