Create common troubleshoot errors page for Autopilot
pantheon-systems/documentation pull request #6468
Opened 2021-06-10 18:14 UTC by joa-pan

Pull requests should be opened in a branch off the `main` branch. For more information on contributing to Pantheon documentation, see the [Contributor Guidelines](https://pantheon.io/docs/contribute). Please refer to our [Style Guide](https://pantheon.io/docs/style-guide) and [this reference](https://developers.google.com/style) for formatting recommendations when contributing to the docs. 

Closes #

## Summary

**[Doc Page Title](https://pantheon.io/docs/doc-title)** -  <Enter a one sentence summation of the pertinent changes (including not-yet-completed work) provided by this PR.>

## Effect

The following changes are already committed:

*
*

## Remaining Work

The following changes still need to be completed:

- [ ] List any outstanding work here

--------------------------------------------------
## Post Launch

**Do not remove** - To be completed by the docs team upon merge:

- [ ] Redirect `/docs/old-path/` => `/docs/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] For Heroes - add a props post to the [discussion board](https://discuss.pantheon.io/c/pantheon-platform/documentation/17).
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

2021-07-28 15:20 UTC, joa-pan commented
@EdwardAngert When you have a moment, can you please review?

2021-07-29 19:18 UTC, greg-1-anderson commented on source/content/guides/autopilot/04-troubleshoot.md
> +Autopilot only works on Drupal sites that are running Drush 8. Drush 5/7/9/10 are not supported.
Note that this limitation does not apply to sites that are Composer-managed. Composer-managed sites should use Drush 10; they should not receive the Drush version error.

Note that currently, Autopilot only supports Integrated Composer; build tools sites cannot be updated.

2021-08-02 14:33 UTC, EdwardAngert requested changes

2021-08-02 14:33 UTC, EdwardAngert commented on source/content/guides/autopilot/04-troubleshoot.md
> +Trigger a workflow to refresh extensions from the GraphQL Playground with the following code change:
can you give users a quick line about how they can access the GraphQL Playground or point to other docs? I thought this was internal only

2021-08-02 14:33 UTC, EdwardAngert commented on source/content/guides/autopilot/04-troubleshoot.md
> +Contact an Autopilot engineer to check the state machine logs, which requires AWS access.
not sure how users would contact an Autopilot engineer. Should we just have them contact Support?

2021-08-02 14:33 UTC, EdwardAngert commented on source/content/guides/autopilot/04-troubleshoot.md
> +Since the Autopilot plan is only set after Autopilot is initialized, the list of elements is unavailable when Autopilot is started for the first time.
I want to reword the `Autopilot plan` part, but I'm not sure what to. Maybe about when the Autopilot feature is initialized? "Plan" sounds more internal.

2021-08-02 14:33 UTC, EdwardAngert commented on source/content/guides/autopilot/04-troubleshoot.md
> +When Autopilot is started for the first time or the Slow Converge feature is used, refresh the extensions list used for exclusions.
Slow Converge? isn't that a CSE only thing?

2021-08-05 12:02 UTC, merged