6607: pm:list instead of pm:projectinfo
pantheon-systems/documentation pull request #6659
Opened 2021-09-02 19:20 UTC by EdwardAngert

Closes #6607 

## Summary

**[Upgrade from Drupal 8](https://pantheon.io/docs/guides/drupal-9-migration/upgrade-to-d9#modules-and-themes)** - List modules and themes using `pm:list` instead of `pm:projectinfo`.

## Effect

The following changes are already committed:

*
*

## Remaining Work

The following changes still need to be completed:

- [ ] List any outstanding work here

--------------------------------------------------
## Post Launch

**Do not remove** - To be completed by the docs team upon merge:
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

2021-09-02 19:25 UTC, pantheondocs commented
Lighthouse Audit Results:

| Description | [Live](https://pantheon.io/docs) | [pr-6659](https://pr-6659--pantheon-docs.my.pantheonfrontend.website/docs) | Difference |
| --- | --- | --- | --- |
| Performance Score | `59` | `67` | `8` |
| Best Practice Score | `79` | `79` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `96` | `96` | `0` |

Lighthouse Audit Reports:

- [`pr-6659` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/29923/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/29923/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)


[Preview Environment](https://pr-6659--pantheon-docs.my.pantheonfrontend.website/docs)

2021-09-02 19:26 UTC, greg-1-anderson requested changes
Users who are following this guide should be using Drush 8 with their Drupal 8 site. `pm:projectinfo`, not `pm:list` should be used to find the projects installed on the Drupal site.

`pm:list` is quite different from `pm:projectinfo`. It returns the list of extensions. There might be more than one extension per project. There is a 1:1 mapping between a Drupal project and a Composer project. If you look at the list of extensions with pm:list, it's not clear what the projects are. I recommend leaving this as it is, perhaps with a note that they should switch back to Drush 8 if necessary to do this conversion.

2021-09-02 20:01 UTC, EdwardAngert commented
Thanks, @greg-1-anderson!

This came up because @justkristin reported in #6607 

that

```
terminus drush $SITE.dev -- pm:projectinfo --fields=name,version --format=table
```

didn't work for them without moving the `--` to between `pm:projectinfo` and the options
so, the example they gave as successful is:

```
terminus drush $SITE.dev pm:projectinfo -- --fields=name,version --format=table
```

which I think I've seen as an occasional Terminus peculiarity (or sometimes an OS autocorrect "feature" that changes `--` to an em dash instead¹ ), and was trying to circumvent entirely

¹ which is not what I think is happening here

2021-09-02 20:38 UTC, EdwardAngert commented
bringing this from the slack discussion 
since D9 folks are using Drush 10, they can use this to list out contrib modules/themes

I'll add it as an alternative and in other parts of the guide where folks are more likely to be on Drush 10

```
terminus drush $SITE.dev pm:list -- --fields=name,version,project --format=table --filter=project~=#.#
```

2021-09-03 00:36 UTC, greg-1-anderson commented on source/content/guides/drupal-9-migration/04-migrate-manual-d9.md
> +  terminus drush $D8_SITE.dev pm:projectinfo -- --status=enabled --fields=name,version --format=table
These two commands should be the same.

2021-09-03 00:38 UTC, greg-1-anderson commented on source/content/guides/drupal-9-migration/04-migrate-manual-d9.md
> +  terminus drush $D8_SITE.dev pm:projectinfo -- --status=enabled --fields=name,version --format=table
I read the original report again; perhaps the `--` in the first version was overlooked. It might be more obvious in the second position.

2021-09-03 00:38 UTC, greg-1-anderson approved these changes

2021-09-21 15:35 UTC, michellecolon-pantheon approved these changes
LGTM

2021-09-21 15:36 UTC, merged