[CMS-391] Modify docs to reflect WP Cron changes
pantheon-systems/documentation pull request #7229
Opened 2022-04-01 17:06 UTC by jspellman814

## Summary

[Cron for WordPress](https://pantheon.io/docs/wordpress-cron) - These documentation updates are based on the WP Cron changes being implemented in [#312](https://github.com/pantheon-systems/WordPress/pull/312) and [#9](https://github.com/pantheon-upstreams/wordpress-project/pull/9).

### Dependencies and Timing

- [x] PR [#312](https://github.com/pantheon-systems/WordPress/pull/312) is merged
- [x] PR [#9](https://github.com/pantheon-upstreams/wordpress-project/pull/9) is merged
- [x] After the next major/minor version of WordPress has been merged into the two repos above.

**Release**:
- [ ] After the dependencies above have been merged

--------------------------------------------------

## Post Launch

**Do not remove** - To be completed by the docs team upon merge:

- [ ] Redirect `/docs/old-path/` => `/docs/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] For Heroes - add a props post to the [discussion board](https://discuss.pantheon.io/c/pantheon-platform/documentation/17).
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

2022-04-01 17:11 UTC, pantheondocs commented
Lighthouse Audit Results:

| Description | [Live](https://pantheon.io/docs) | [pr-7229](https://pr-7229--pantheon-docs.my.pantheonfrontend.website/docs) | Difference |
| --- | --- | --- | --- |
| Performance Score | `52` | `54` | `2` |
| Best Practice Score | `86` | `86` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `98` | `98` | `0` |

Lighthouse Audit Reports:

- [`pr-7229` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/35483/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/35483/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)


[Preview Environment](https://pr-7229--pantheon-docs.my.pantheonfrontend.website/docs)

2022-04-04 19:48 UTC, CdrMarks requested changes

2022-04-04 19:48 UTC, CdrMarks commented on source/content/wordpress-cron.md
> +By default, Pantheon's WordPress upstreams have WP_CRON disabled. If you wish to continue using WP_CRON, you will need to add the code below to your `wp-config.php` file to enable WP-Cron's internal
@jspellman814 It'll be important to not the added line needs to be above the `require_once` of the `wp-config-pantheon.php` file.

2022-04-04 20:06 UTC, CdrMarks approved these changes

2022-04-04 20:18 UTC, CdrMarks commented
[Preview](https://pr-7229--pantheon-docs.my.pantheonfrontend.website/docs/wordpress-cron)

2022-04-04 20:20 UTC, CdrMarks requested changes

2022-04-04 20:20 UTC, CdrMarks commented on source/content/wordpress-cron.md
> +By default, Pantheon's WordPress upstreams have WP_CRON disabled. If you wish to continue using WP_CRON, you will need to add the code below to your `wp-config.php` file to enable WP-Cron's internal
```suggestion
By default, Pantheon's WordPress upstreams have WP-CRON disabled. If you wish to continue using WP-CRON, you will need to add the code below to your `wp-config.php` file to enable WP-Cron's internal processing. This line needs to be above the `require_once` expression that pulls in `wp-config-pantheon.php`.
```

2022-04-04 20:22 UTC, CdrMarks requested changes

2022-04-04 20:22 UTC, CdrMarks commented on source/content/wordpress-cron.md
> +By default, Pantheon's WordPress upstreams have WP-CRON disabled. If you wish to continue using WP-CRON, you will need to add the code below to your `wp-config.php` file to enable WP-Cron's internal
```suggestion
By default, Pantheon's WordPress upstreams have WP-Cron disabled. If you wish to continue using WP-Cron, you will need to add the code below to your `wp-config.php` file to enable WP-Cron's internal processing. This line needs to be above the `require_once` expression that pulls in `wp-config-pantheon.php`.
```

2022-04-04 20:23 UTC, CdrMarks approved these changes

2022-04-04 20:33 UTC, greg-1-anderson approved these changes
Good to go once https://github.com/pantheon-systems/WordPress/pull/312 is merged.

2022-04-05 20:37 UTC, jspellman814 commented
@whitneymeredith @pantheondocs The next version of WordPress has been [merged](https://github.com/pantheon-systems/WordPress/pull/321), and the documented changes to WP-Cron are now in place. This PR is ready to merge ASAP.

2022-04-05 20:47 UTC, merged