Replace Autopilot Compatibility Image with Accessible Table
pantheon-systems/documentation pull request #7363
Opened 2022-05-25 17:22 UTC by whitneymeredith

Closes #7358 

## Summary

**[Autopilot Site Compatibility](https://pantheon.io/docs/guides/autopilot#autopilot-site-compatibility)** - Replaced Autopilot Site Compatibility diagram with a more accessible table.

## Effect

The following changes are already committed:

*
*

## Remaining Work and Prerequisites

The following changes still need to be completed:

- [ ] List any outstanding work here

### Dependencies and Timing

- [ ] Other prerequisites that must be completed before merging this PR

**Release**:
- [ ] When ready
- [ ] After date: $DATE

--------------------------------------------------

## Post Launch

**Do not remove** - To be completed by the docs team upon merge:

- [ ] Redirect `/docs/old-path/` => `/docs/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] For Heroes - add a props post to the [discussion board](https://discuss.pantheon.io/c/pantheon-platform/documentation/17).
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

2022-05-26 19:24 UTC, whitneymeredith commented
[Preview](https://pr-7363--pantheon-docs.my.pantheonfrontend.website/docs/guides/autopilot#autopilot-site-compatibility)

2022-06-01 19:05 UTC, kelly-mcgonnigle requested changes

2022-06-01 19:09 UTC, whitneymeredith reviewed
LGTM

2022-06-01 20:45 UTC, wordsmither commented
lgtm

2022-06-01 20:45 UTC, merged