Update cookies.md for clearer regex explanation
pantheon-systems/documentation pull request #7499
Opened 2022-07-15 14:57 UTC by conorbauer23

Closes #

## Summary

**[Working with Cookies on Pantheon](https://pantheon.io/docs/cookies)** - Current cookies page lists a regex, which is sort of clear to developers, but not clear to non-developers. Let's make it easy by clearly stating it's a regex that is required, and supplying a path to check for regex compatibility.

**Release**:
- [x] When ready
- [ ] After date: $DATE

--------------------------------------------------

## Post Launch

**Do not remove** - To be completed by the docs team upon merge:

- [ ] Redirect `/docs/old-path/` => `/docs/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] For Heroes - add a props post to the [discussion board](https://discuss.pantheon.io/c/pantheon-platform/documentation/17).
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

2022-07-15 14:58 UTC, conorbauer23 commented
@CdrMarks Anything you want to add to this one? I think we discussed this recently.

2022-07-15 18:55 UTC, CdrMarks requested changes
I've made a suggestion.  If you like it, there is a link to accept the suggestion.

2022-07-15 18:55 UTC, CdrMarks commented on source/content/cookies.md
> +Respond to a request with cached content depending on the presence and value of a particular cookie. It's important to note that in order for the response to be cached by Pantheon's Edge, the cookie
I would like to see some changes, such as this, made to this PR:
```suggestion
Respond to a request with cached content depending on the presence and value of a particular cookie. It's important to note that in order for the response to be cached by Pantheon's Edge, the cookie name must follow these naming rules:
* Must begin with the 7 capital letters `STYXKEY`
* Must have one or more of the following:
	* letters `a-z` and `A-Z`
	* numbers `0-9`
	* underscore `_`
	* hyphen `-`

If you prefer a regular expression, the name must match the following format: `STYXKEY[a-zA-Z0-9_-]+`. Test your cookie with [Regex 101.](https://regex101.com/) 
```

2022-07-15 18:58 UTC, conorbauer23 commented
Suggestion accepted! Thanks @CdrMarks

2022-07-15 18:59 UTC, CdrMarks approved these changes

2022-07-15 21:37 UTC, closed without merging

2022-07-16 01:01 UTC, CdrMarks commented
@whitneymeredith was there something wrong with this PR.  I'm confused why this one was closed and 7500 was merged instead?

2022-07-18 14:40 UTC, whitneymeredith commented
@CdrMarks I received an error (error: pathspec did not find a match) when I tried to check out Conor's branch on my local.