Object Cache Guide
pantheon-systems/documentation pull request #7689
Opened 2022-09-12 22:21 UTC by whitneymeredith

Closes # [DOC-686](https://getpantheon.atlassian.net/jira/software/projects/DOC/boards/186?selectedIssue=DOC-686)

## Summary

**[Object Cache Guide](https://pantheon.io/docs/doc-title)** - Break out the Object Cache doc into an easy-to-scan guide.

## Effect

The following changes are already committed:

*
*

## Remaining Work and Prerequisites

The following changes still need to be completed:

- [ ] List any outstanding work here

### Dependencies and Timing

- [ ] Other prerequisites that must be completed before merging this PR

**Release**:
- [ ] When ready
- [ ] After date: $DATE

--------------------------------------------------

## Post Launch

**Do not remove** - To be completed by the docs team upon merge:

- [ ] Redirect `/docs/old-path/` => `/docs/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] For Heroes - add a props post to the [discussion board](https://discuss.pantheon.io/c/pantheon-platform/documentation/17).
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

2022-09-12 22:27 UTC, pantheondocs commented
Lighthouse Audit Results:

| Description | [Live](https://pantheon.io/docs) | [pr-7689](https://pr-7689--pantheon-docs.my.pantheonfrontend.website/docs) | Difference |
| --- | --- | --- | --- |
| Performance Score | `46` | `49` | `3` |
| Best Practice Score | `86` | `86` | `0` |
| SEO Score | `96` | `96` | `0` |
| Accessibility Score | `98` | `98` | `0` |

Lighthouse Audit Reports:

- [`pr-7689` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/41680/artifacts/0//lighthouse_data/lighthouse-audit-dev.html)
- [`Pantheon Docs` HTML Report](https://circleci.com/gh/pantheon-systems/documentation/41680/artifacts/0//lighthouse_data/lighthouse-audit-reference.html)


[Preview Environment](https://pr-7689--pantheon-docs.my.pantheonfrontend.website/docs)

2022-09-13 15:43 UTC, whitneymeredith commented
[Preview](https://pr-7689--pantheon-docs.my.pantheonfrontend.website/docs/guides/object-cache)

2022-09-19 15:28 UTC, whitneymeredith commented
Redirect needed:
/docs/object-cache — > /guides/object-cache

2022-09-19 18:55 UTC, jms-pantheon requested changes
Just a few changes to layout and More Resources, thanks!

2022-09-19 18:55 UTC, jms-pantheon commented on source/content/guides/object-cache/03-redis-command-line.md
> +## More Resources
These resources aren't relevant to the page, not that we're using a local "terminal" here but not the Pantheon "Terminus" tool. The other, this is the Redis command line interface (CLI) but does not relate to the WordPress CLI

2022-09-19 18:55 UTC, jms-pantheon commented on source/content/guides/object-cache/04-remove-object-cache.md
> +showtoc: true
Could drop TOC here too, just the one item

2022-09-19 18:55 UTC, jms-pantheon commented on source/content/guides/object-cache/05-troubleshoot-object-cache.md
> +- [site.env](/terminus/examples#siteenv)
This Terminus command isn't used in this guide, I suggest removing it

2022-09-20 15:53 UTC, wordsmither commented
lgtm

2022-09-20 17:41 UTC, merged

2022-09-23 14:38 UTC, jms-pantheon commented
@whitneymeredith should the old long doc be removed and redirected as part of this?