Detailed Product Overview: Custom Upstreams
pantheon-systems/documentation pull request #8249
Opened 2023-03-17 15:50 UTC by wordsmither

Closes #DOCO-930

## Summary

**[Custom Upstreams](https://docs.pantheon.io/overview/custom-upstreams)** - New product overview page. One of many to come.

## Effect

The following changes are already committed:

*
*

## Remaining Work and Prerequisites

The following changes still need to be completed:

- [ ] List any outstanding work here

### Dependencies and Timing

- [ ] Other prerequisites that must be completed before merging this PR

**Release**:
- [ ] When ready
- [ ] After date: $DATE

--------------------------------------------------

## Post Launch

**Do not remove** - To be completed by the docs team upon merge:

- [ ] Redirect `/old-path/` => `/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] For Heroes - add a props post to the [discussion board](https://discuss.pantheon.io/c/pantheon-platform/documentation/17).
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

2023-03-17 16:49 UTC, wordsmither commented
[Preview](https://pr-8249-documentation.appa.pantheon.site/overview/custom-upstreams)

2023-05-20 00:48 UTC, jsulz commented on source/content/overview/custom-upstreams.md
> +* [Account holders](https://dashboard.pantheon.io/workspace/ee3995c4-652e-44a0-b00b-0085e92d78da/support)
Same note as on the New Relic review - this link 404s.

2023-05-20 00:49 UTC, jsulz requested changes
Looks correct; no issues with the content, just one requested change.

2023-05-22 16:35 UTC, whitneymeredith approved these changes
LGTM

2023-05-22 16:35 UTC, merged