FES Robots and Indexing
pantheon-systems/documentation pull request #8588
Opened 2023-06-29 21:25 UTC by whitneymeredith

Closes #8585 

## Summary

**[Robots and Indexing](https://docs.pantheon.io/guides/decoupled/wp-nextjs-frontend-starters/robots-indexing)** - Adds new pages to document how users of Next.js (WP and Drupal) and Gatsby (WP only) frameworks can use a robots.txt file on their Front-End Sites.

## Effect

The following changes are already committed:

*
*

## Remaining Work and Prerequisites

The following changes still need to be completed:

- [ ] List any outstanding work here

### Dependencies and Timing

- [ ] Other prerequisites that must be completed before merging this PR

**Release**:
- [ ] When ready
- [ ] After date: $DATE

--------------------------------------------------

## Post Launch

**Do not remove** - To be completed by the docs team upon merge:

- [ ] Redirect `/old-path/` => `/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] For Heroes - add a props post to the [discussion board](https://discuss.pantheon.io/c/pantheon-platform/documentation/17).
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

2023-07-05 18:55 UTC, CobyPear requested changes
Looks great overall– just a few picky things in the comments.

2023-07-05 18:55 UTC, CobyPear commented on source/content/partials/decoupled-nextjs-robots.md
> +    ```bash{promptUser: user}
Can this be a regular text file? The bash prompt renders the `$` on each line of the output which is a bit confusing

2023-07-05 18:55 UTC, CobyPear commented on source/content/guides/decoupled/wp-gatsby-frontend-starters/05-robots-indexing.md
> +    ```bash{promptUser: user}
```suggestion
    ```javascript
```
This one can be `javascript` if that is supported.

2023-07-05 18:55 UTC, CobyPear commented on source/content/guides/decoupled/wp-gatsby-frontend-starters/05-robots-indexing.md
> +     ```bash{promptUser: user}
Same here
```suggestion
     ```javascript
```

2023-07-05 18:55 UTC, CobyPear commented on source/content/guides/decoupled/wp-gatsby-frontend-starters/05-robots-indexing.md
> +            sitemap: 'https://www.mygatsbysite.com/sitemap.xml',
```suggestion
            host: 'https://www.mygatsbysite.example',
            sitemap: 'https://www.mygatsbysite.example/sitemap.xml',
```
I learned about this the other day: use `.example` or `example.com` as the domain for documenting examples
https://datatracker.ietf.org/doc/html/rfc2606#section-2

2023-07-05 20:46 UTC, CobyPear approved these changes

2023-07-06 16:54 UTC, wordsmither approved these changes
lgtm

2023-07-06 16:54 UTC, merged