[CMSP-496] multisite workflows update
pantheon-systems/documentation pull request #8605
Opened 2023-07-10 21:37 UTC by jazzsequence

keep the manual terminus info under the heading Run WP-CLI search-replace manually

Closes #

## Summary

**[Doc Page Title](https://docs.pantheon.io/doc-title)** - <Enter a one sentence summation of the pertinent changes (including not-yet-completed work) provided by this PR.>

## Effect

The following changes are already committed:

*
*

## Remaining Work and Prerequisites

The following changes still need to be completed:

- [ ] List any outstanding work here

### Dependencies and Timing

- [ ] Other prerequisites that must be completed before merging this PR

**Release**:
- [ ] When ready
- [ ] After date: $DATE

--------------------------------------------------

## Post Launch

**Do not remove** - To be completed by the docs team upon merge:

- [ ] Redirect `/old-path/` => `/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] For Heroes - add a props post to the [discussion board](https://discuss.pantheon.io/c/pantheon-platform/documentation/17).
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

2023-07-11 17:13 UTC, scottbuscemi requested changes

2023-07-12 21:08 UTC, jazzsequence commented on source/content/guides/multisite/05-workflows.md
>  After you've configured a WordPress Multisite in the Dev environment, you'll quickly want to promote it to Test and then Live. Before you use these environments, you'll need to initialize them.
Done!

2023-07-13 19:04 UTC, pwtyler commented on source/content/guides/multisite/05-workflows.md
>  ## Refresh Data from Live
This should be bucketed under manual steps, and/or have a note pointing back to the search_replace doc.

2023-07-13 19:33 UTC, pwtyler approved these changes

2023-07-14 01:37 UTC, scottbuscemi approved these changes
LGTM

2023-07-14 16:31 UTC, merged