Front end sites v1 pipeline docs updates
pantheon-systems/documentation pull request #8737
Opened 2023-10-12 16:46 UTC by stevector

Closes #

## Summary

**[Doc Page Title](https://docs.pantheon.io/doc-title)** - <Enter a one sentence summation of the pertinent changes (including not-yet-completed work) provided by this PR.>

## Effect

The following changes are already committed:

*
*

## Remaining Work and Prerequisites

The following changes still need to be completed:

- [ ] List any outstanding work here

### Dependencies and Timing

- [ ] Other prerequisites that must be completed before merging this PR

**Release**:
- [ ] When ready
- [ ] After date: $DATE

--------------------------------------------------

## Post Launch

**Do not remove** - To be completed by the docs team upon merge:

- [ ] Redirect `/old-path/` => `/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] For Heroes - add a props post to the [discussion board](https://discuss.pantheon.io/c/pantheon-platform/documentation/17).
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

2023-10-24 14:43 UTC, stevector commented
@jsulz can you review?

2023-10-27 00:16 UTC, jsulz commented on source/images/decoupled/purge-build-cachge--trigger.png
I would update this screenshot with something in production. I was grabbing this from a Figma file, which also included the CDN cache purging work, but this is not available to customers.

2023-10-27 17:46 UTC, stevector commented on source/images/decoupled/purge-build-cachge--trigger.png
Will do. And I see I mispelled a word in this file name

2023-10-27 18:04 UTC, rachelwhitton commented on source/content/guides/decoupled/overview/10-v1-pipeline.md
> +Among under-the-hood-optimizations, like [caching of folders between builds](/guides/decoupled/overview/manage-settings#build-cache), [the new pipeline now uses your `package.json` file](/guides/deco
> to select the appropriate version of Node.js your build and your runtime environments.

missing for, maybe? 

> to select the appropriate version of Node.js for your build and your runtime environments.

2023-10-30 20:57 UTC, stevector commented on source/content/guides/decoupled/overview/10-v1-pipeline.md
> +Among under-the-hood-optimizations, like [caching of folders between builds](/guides/decoupled/overview/manage-settings#build-cache), [the new pipeline now uses your `package.json` file](/guides/deco
good catch!

2023-10-30 21:51 UTC, stevector commented on source/images/decoupled/purge-build-cachge--trigger.png
done!

2023-10-30 21:51 UTC, stevector commented
@rachelwhitton can you review one more time and then merge tomorrow or Wednesday?

2023-10-31 14:04 UTC, rachelwhitton commented on source/content/guides/decoupled/overview/05-manage-settings.md
> +Non-LTS versions like v17 are not available.
> Non-LTS versions like v17 are not available.

I suggest removing this sentence or revising it for accuracy based on https://nodejs.org/en/about/previous-releases  (which suggests v16 is also Non-LTS ?) 

If revising, I suggest adding context for "Non-LTS" maybe in a [tooltip](https://docs.pantheon.io/style-guide#tooltips)

2023-10-31 14:09 UTC, rachelwhitton commented on source/content/guides/decoupled/overview/05-manage-settings.md
> +```json
Make it more clear what file this excerpt is from by adding a title: https://docs.pantheon.io/style-guide#file-excerpts 
```suggestion
```json:title=package.json
```

2023-10-31 14:11 UTC, rachelwhitton commented on source/content/guides/decoupled/overview/05-manage-settings.md
> +Sites made prior to DATE set the Node.js version via  `.nvmrc` and can select via:
@stevector is DATE a placeholder here maybe?

2023-10-31 14:14 UTC, rachelwhitton commented on source/content/guides/decoupled/overview/05-manage-settings.md
> +The first build on any environment (production or either type of Multidevs) runs without a cache. During the first build, Pantheon caches the following assets based on the framework you’ve selected:
```suggestion
The first build on any environment ([production or either type of Multidevs](/guides/decoupled/overview/considerations#types-of-environments)) runs without a cache. During the first build, Pantheon caches the following assets based on the framework you’ve selected:
```

2023-10-31 14:17 UTC, rachelwhitton requested changes
Some minor suggestions requested for consideration

2023-10-31 16:33 UTC, rachelwhitton commented on source/content/guides/decoupled/overview/05-manage-settings.md
> +Sites made prior to DATE set the Node.js version via  `.nvmrc` and can select via:
```suggestion
Sites made prior to DATE set the Node.js version via  `.nvmrc` and can select via:
```

2023-10-31 16:41 UTC, rachelwhitton approved these changes

2023-10-31 17:56 UTC, merged