WordPress 6.4.3 Release Note
pantheon-systems/documentation pull request #8853
Opened 2024-01-31 19:27 UTC by pwtyler

## Summary

**[Pantheon Release Notes](https://docs.pantheon.io/release-notes/)** - Adds release note for WordPress 6.4.3

## Remaining Work and Prerequisites

The following changes still need to be completed:

- [ ] Copy Editing
- [ ] I'd like to include a link to the WordPress.org blog post in this post, but unsure of where/phrasing.

**Release**:
- [x] When ready

--------------------------------------------------

## Post Launch

**Do not remove** - To be completed by the docs team upon merge:

- [ ] Redirect `/old-path/` => `/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] For Heroes - add a props post to the [discussion board](https://discuss.pantheon.io/c/pantheon-platform/documentation/17).
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

2024-01-31 20:45 UTC, jazzsequence requested changes

2024-01-31 20:45 UTC, jazzsequence commented on source/releasenotes/2024-01-31-wordpress-6-4-3.md
> +* **Security updates:** Addressed two security vulnerabilities, including a PHP file upload bypass (limited to administrators), and a object injection gadget that could be used to exploit an existing
> object injection gadget

I'm not sure what an "object injection gadget" is in this context. Can you use something else to describe the "gadget"?

2024-01-31 20:58 UTC, pwtyler commented on source/releasenotes/2024-01-31-wordpress-6-4-3.md
> +* **Security updates:** Addressed two security vulnerabilities, including a PHP file upload bypass (limited to administrators), and a object injection gadget that could be used to exploit an existing
A mechanism to exploit another vulnerability is what it really means, but I agree it's still more jargon than I'd like I'll think on it.

2024-02-01 19:10 UTC, pwtyler commented on source/releasenotes/2024-01-31-wordpress-6-4-3.md
> +* **Security updates:** Addressed two security vulnerabilities, including a PHP file upload bypass (limited to administrators), and a object injection gadget that could be used to exploit an existing
```suggestion
* **Security updates:** Addressed two security vulnerabilities, including a PHP file upload bypass (limited to administrators), and a object injection mechanism that could be used to exploit an existing Remote Code Execution (RCE) vulnerability. For a detailed analysis of the two security patches, see [this article from Patchstack](https://patchstack.com/articles/wordpress-6-4-3-security-release/).
```

2024-02-01 21:05 UTC, jazzsequence commented on source/releasenotes/2024-01-31-wordpress-6-4-3.md
> +The latest version of WordPress, 6.4.3, became available on Pantheon as of January 30, 2024.
link the WP release notes here
```suggestion
The latest version of WordPress, [6.4.3](https://wordpress.org/news/2024/01/wordpress-6-4-3-maintenance-and-security-release/), became available on Pantheon as of January 30, 2024.
```

2024-02-01 21:05 UTC, jazzsequence commented on source/releasenotes/2024-01-31-wordpress-6-4-3.md
> +<!--- // TODO insert link to https://wordpress.org/news/2024/01/wordpress-6-4-3-maintenance-and-security-release/ somewhere in here -->
obvs drop TODO
```suggestion
```

2024-02-01 21:30 UTC, jazzsequence approved these changes

2024-02-01 21:32 UTC, merged