[CMSP-918] Drupal 7.100 release
pantheon-systems/documentation pull request #8885
Opened 2024-03-08 23:04 UTC by pwtyler

## Summary
- Adds changelog record for Drupal 7.100

**[Pantheon Release Notes](https://docs.pantheon.io/release-notes)** - New release note for D7.100

**Release**:
- [x] When ready
- [ ] After date: $DATE

--------------------------------------------------

## Post Launch

**Do not remove** - To be completed by the docs team upon merge:

- [ ] Redirect `/old-path/` => `/new-path/` (if applicable)
- [ ] Include/exclude pages ^ respectively within docs search service provider (if applicable)
- [ ] For Heroes - add a props post to the [discussion board](https://discuss.pantheon.io/c/pantheon-platform/documentation/17).
- [ ] Remove from the [project board](https://github.com/pantheon-systems/documentation/projects/14)

2024-03-08 23:23 UTC, pwtyler commented on source/releasenotes/2024-03-08-drupal-7-100.md
> +The latest version of Drupal 7, [7.100](https://www.drupal.org/project/drupal/releases/7.100), became available on Pantheon as of March 8, 20204.
```suggestion
The latest version of Drupal 7, [7.100](https://www.drupal.org/project/drupal/releases/7.100), became available on Pantheon as of March 8, 2024.
```

2024-03-09 00:02 UTC, pwtyler commented
Link direct to changelog entry:
https://pr-8885-documentation.appa.pantheon.site/release-notes/2024/03/drupal-7-100

2024-03-09 00:02 UTC, pwtyler commented on source/releasenotes/2024-03-08-drupal-7-100.md
> +* **Bug fixes and security hardening** In addition to the Announcements Module, the release includes a few bug fixes and feature improvements. No security fixes are included in this release. For full
```suggestion
* **Bug fixes and security hardening** In addition to the Announcements module, the release includes a few bug fixes and feature improvements. No security fixes are included in this release. For full details, see the release notes [on Drupal.org](https://www.drupal.org/project/drupal/releases/7.100).
```

2024-03-11 16:11 UTC, stevector requested changes
We need clearer language than
> Support for Drupal 7 is ending on 5 January 2025.

People will read that and assume that they can't run Drupal 7 on Pantheon after that date which isn't the case.

2024-03-11 16:23 UTC, pwtyler commented on source/releasenotes/2024-03-08-drupal-7-100.md
> +Support for Drupal 7 is ending on 5 January 2025.
```suggestion
```
That's a larger conversation that doesn't need to block getting this out.

2024-03-11 16:51 UTC, scottbuscemi approved these changes

2024-03-11 16:58 UTC, stevector approved these changes
Thanks!

2024-03-11 16:58 UTC, merged