WIP - mdx and import ordering
pantheon-systems/documentation pull request #8968
Opened 2024-04-26 01:42 UTC by stevector

2024-04-26 15:45 UTC, stevector commented
@mel-miller This PR is not at all urgent. Just some clean up that should get your review.

2024-04-30 17:30 UTC, mel-miller approved these changes
Works for me.

2024-04-30 18:13 UTC, stevector commented
I just resolved the merge conflicts with `main`

2024-05-09 18:06 UTC, rachelwhitton commented
@stevector I added local VRT here in this PR, can you take a look? On another branch I got 8 scenarios passed (screenshot of that has been added to the description at the top of this PR), but on this branch the test result is showing me 4 pages and 4 failed 

![screencapture-file-Users-rachelwhitton-documentation-backstop-data-html-report-index-html-2024-05-09-13_05_39](https://github.com/pantheon-systems/documentation/assets/10119525/70eb8a09-b39e-4512-b19f-bb8c40b364a4)

2024-05-09 22:16 UTC, rachelwhitton requested changes
@stevector I added local VRT here in this PR, can you take a look? On another branch I got 8 scenarios passed (screenshot of that has been added to the description at the top of this PR), but on this branch the test result is showing me 4 passed and 4 failed 

The TOC stopped working across various templates, for example: 
* https://pr-8968-documentation.appa.pantheon.site/guides/mariadb-mysql/kill-mysql-queries
* https://pr-8968-documentation.appa.pantheon.site/certification/study-guide
* https://pr-8968-documentation.appa.pantheon.site/drupal-cron

Headers are smaller in the preview environment compared to production 

![screencapture-file-Users-rachelwhitton-documentation-backstop-data-html-report-index-html-2024-05-09-13_05_39](https://github.com/pantheon-systems/documentation/assets/10119525/70eb8a09-b39e-4512-b19f-bb8c40b364a4)

2024-05-10 16:51 UTC, rachelwhitton commented on backstop.json
> +  "onReadyScript": "puppet/onReady.js",
These 2 lines were copied in from an example config file, I think we can remove?  

```
CREATING NEW REFERENCE FILE
WARNING: script not found: /Users/rachelwhitton/documentation/backstop_data/engine_scripts/puppet/onBefore.js
Browser Console Log 0: JSHandle:BackstopTools have been installed.
Browser Console Log 0: JSHandle:BackstopTools have been installed.
Browser Console Log 0: JSHandle:BackstopTools have been installed.
Browser Console Log 0: JSHandle:BackstopTools have been installed.
Browser Console Log 0: JSHandle:BackstopTools have been installed.
Browser Console Log 0: JSHandle:BackstopTools have been installed.
Browser Console Log 0: JSHandle:BackstopTools have been installed.
Browser Console Log 0: JSHandle:BackstopTools have been installed.
WARNING: script not found: /Users/rachelwhitton/documentation/backstop_data/engine_scripts/puppet/onReady.js
```

2024-05-13 20:34 UTC, stevector commented
> The TOC stopped working across various templates

@rachelwhitton I'm reassigning to myself to investigate that

2024-05-13 21:07 UTC, stevector commented
@rachelwhitton I figure out why the Table of Contents stopped working.

In the PR that created Release Notes (#8802) I created the `MdxWrapper` component. In creating that component I tried to consolidate as many of the `shortcodes` passed in to mdx from other templates including this one from the old `changelogs` template. https://github.com/pantheon-systems/documentation/blob/87ec5f58079b9876861564984b07da632a837bf8/src/templates/changelogs.js#L23

That `releaseHeadlines` component appears to exist only to _exclude_ headings from TOCs (because) on the old changelog you won't want every heading on the TOC, just the main headline (the month).

Anyway, I don't think we need the `releaseHeadlines` component at all anymore.

2024-05-13 21:07 UTC, stevector commented
I'll keep this PR assigned to myself to continue poking at VRT, at least until our 1:1 tomorrow.

2024-05-13 21:14 UTC, stevector commented
> Anyway, I don't think we need the releaseHeadlines component at all anymore

🙃 No, it's used elsewhere so I'll keep the component, just remove this particular usage.

2024-06-11 17:01 UTC, rachelwhitton commented
I removed backstop from this PR and merged main then ran VRT locally and 0 passed 

![screencapture-localhost-9323-2024-06-11-11_59_14](https://github.com/pantheon-systems/documentation/assets/10119525/a3f6182e-62aa-4ac9-a33b-0ed45aceee00)

2024-06-12 18:18 UTC, stevector commented
@rachelwhitton, I think this PR is ready to merge now. I ran VRT locally and just got some false positives

2024-06-12 19:39 UTC, rachelwhitton approved these changes

2024-06-12 19:41 UTC, merged