Ingrid kwok patch 10
pantheon-systems/documentation pull request #9026
Opened 2024-06-04 21:36 UTC by IngridKwok

## Summary

Please merge to main and publish release note. 

**Release**:
- [x ] When ready

--------------------------------------------------

2024-06-04 21:37 UTC, IngridKwok commented
@stevector @rachelwhitton Ready to publish after your final review.

2024-06-04 21:51 UTC, scottbuscemi submitted a review, later dismissed

2024-06-04 21:51 UTC, scottbuscemi commented on source/releasenotes/2024-06-04-release-note-multi-select-filter.md
> +We're introducing another enhancement to our release notes: the multi-select filter. Now, you can filter release notes using multiple tags simultaneously, providing a more customized and efficient wa
I believe an extra line below this is needed to add another paragraph.

I wouldn't call out the clear filter button - that's a product spec but not a noteworthy part of this release.

2024-06-04 22:30 UTC, stevector commented on source/releasenotes/2024-06-04-release-note-multi-select-filter.md
> +We're introducing another enhancement to our release notes: the multi-select filter. Now, you can filter release notes using multiple tags simultaneously, providing a more customized and efficient wa
```suggestion
We're introducing another enhancement to our release notes: the multi-select filter. Now, you can filter release notes using multiple tags simultaneously, providing a more customized and efficient way to find relevant updates.
```

I agree we don't need to call that out

2024-06-04 22:30 UTC, stevector commented on source/releasenotes/2024-06-04-release-note-multi-select-filter.md
> +Explore this new functionality and streamline your experience with Pantheon release notes.
```suggestion

Explore this new functionality and streamline your experience with Pantheon release notes.
```

2024-06-04 22:32 UTC, stevector requested changes

2024-06-04 22:32 UTC, stevector commented on source/releasenotes/release-note-multi-select-filter.png
It appears that this image is not used, only the gif, right @IngridKwok? If so, let's delete it.

2024-06-04 22:32 UTC, stevector commented on source/images/release-note-multi-select-filter.png
It appears that this image is not used, only the gif, right @IngridKwok? If so, let's delete it.

2024-06-05 20:54 UTC, IngridKwok commented on source/releasenotes/release-note-multi-select-filter.png
Only gif is used. @stevector

2024-06-05 22:48 UTC, IngridKwok commented
@stevector Ready to publish.

2024-06-06 15:44 UTC, stevector commented
@IngridKwok there are still open comments and suggestions. Can you respond to those?

2024-06-06 16:02 UTC, IngridKwok commented on source/releasenotes/release-note-multi-select-filter.png
@stevector I don't see the option to delete this though. Are you able to delete it?

2024-06-06 17:21 UTC, stevector commented on source/releasenotes/release-note-multi-select-filter.png
@IngridKwok is this `.png` used anywhere?

2024-06-06 17:41 UTC, IngridKwok commented on source/releasenotes/release-note-multi-select-filter.png
No, the multi select filter png was supposed to be used for this release note only, but then I replaced it with the gif so only the gif should be kept. I still couldn't see the option for me to delete the png though.

2024-06-06 20:05 UTC, stevector approved these changes

2024-06-06 20:06 UTC, merged