9082-re-add-prettier
pantheon-systems/documentation pull request #9163
Opened 2024-08-08 20:59 UTC by jazzsequence

## Summary

**[Doc Page Title](https://docs.pantheon.io/doc-title)** - <Enter a one sentence summation of the pertinent changes (including not-yet-completed work) provided by this PR.>

2024-08-13 13:44 UTC, stevector requested changes
The prettier docs discourage using `eslint-plugin-prettier` as the method of executing the prettier check: https://prettier.io/docs/en/integrating-with-linters.html

Here's a summary video: https://www.youtube.com/watch?v=Cd-gBxzcsdA

I haven't yet watched the longer talk: https://www.youtube.com/watch?v=sSJBeWPIipQ&t=0s

I _think_ we should first configure prettier in isolation, and secondarily configure ESLint.

2024-08-13 15:11 UTC, jazzsequence commented
When I dug into Prettier, I discovered that the _whole point_ of it is to edit files. This puts it at odds with [reporting that there are linting issues](https://github.com/pantheon-systems/documentation/issues/9082#issuecomment-2276541994) as opposed to _fixing_ those linting issues. ESLint is a linter and, in this context, it uses the ruleset established by Prettier as the rules it checks against. 

I can remove ESLint, but then we're back to _changing large numbers of files_ (at least the first time it runs) rather than simply _reporting that there are problems_. I could just not commit those changes back to the PR, and report a failure if files were changed by Prettier, but it seems like that maybe defeats the purpose of the tool.

2024-08-13 15:16 UTC, jazzsequence commented
New idea:

* remove ESLint
* run Prettier on PRs. it will change files. the GH action branch will now be ahead of the PR branch.
* run a git diff against the changes Prettier made
* post a comment back on the PR saying "these files have linting issues"
* (optional) maybe output the actual diff in the PR comment as well?

2024-08-13 16:31 UTC, stevector commented
I link that idea, and I'd be fine with the same flow for ESLint, I think we can start with just prettier though (up to you if you'd rather remove ESLint or keep it and add a separate action for it (or add on to the same Action)).

Back to my comment here: https://github.com/pantheon-systems/documentation/issues/9082#issuecomment-2276541994 I was initially hesitant about CI making the change/commit for us because I feared it'd supplant a learning opportunity. But, I see the potential for learning in this flow
* I'm doing development work in a branch
* I push/make a PR
* CI finds and fixes whitespace/etc with a new commit
* I push again
* Push rejected because of conflicts
* I pull and learn

2024-08-13 21:31 UTC, jazzsequence commented
swinging back around to this. 

1. Let's keep ESLint. We'll probably use it in the future.
2. Let's pull the ESLint _action_ out.
3. Let's add a Prettier action that runs on changed files in PRs
  - If files were changed, it will commit the change back to the PR.
  - If it commits back to the PR, it posts a message back to the PR that looks like this: https://github.com/pantheon-systems/wordpress-composer-managed/pull/151#issuecomment-2265620483
4. ESLint checks can come _after_ this workflow. In that way, ESLint would check all the things that Prettier couldn't fix automatically, as well as checking _already fixed_ code.

2024-08-16 15:10 UTC, jazzsequence commented
Example robot comment and change: https://github.com/pantheon-systems/documentation/pull/9180#issuecomment-2292397039

2024-10-07 22:14 UTC, stevector requested changes

2024-10-07 22:14 UTC, stevector commented on eslint.config.js
@jazzsequence I'm still concerned with intermingling prettier and eslint: https://github.com/pantheon-systems/documentation/pull/9163#pullrequestreview-2235602505

I'm fine with having both, and even adding both in the same PR, but understanding is still that it is better to use Prettier directly than having ESLint be the mechanism for running Prettier.

2024-10-08 17:28 UTC, stevector commented on eslint.config.js
Flerp, or maybe I just wasn't looking at the substance of this PR closely enough and it is doing what we want. Although, I'm going to suggest some readme tweaks.

2024-10-08 17:30 UTC, stevector commented on README.md
> +We use ESLint and Prettier to enforce code style. On each pull request to the repository, if any `.js`, `.jsx`, `.ts` or `.tsx` files are modified in the `/src` directory, ESLint will run against our
> ESLint will run against our Prettier configuration to check for code styling issues on the updated/changed files.

I don't think this is accurate. The command run is `npx prettier` (which I think is the command we want)

2024-10-08 17:55 UTC, stevector commented on package.json
> +    "eslint-plugin-prettier": "^5.2.1",
I don't think we need plugin-prettier. Just config-prettier

2024-10-11 19:35 UTC, jazzsequence commented on eslint.config.js
👍

2024-10-11 19:50 UTC, jazzsequence commented
Made the requested changes and the Prettier workflow still seems to be working as expected (see https://github.com/pantheon-systems/documentation/pull/9180#issuecomment-2408033041). 

I'm going to close that other test PR since I think I'm done with the testing, this should be good for you to use @stevector.

2024-10-11 21:01 UTC, stevector commented on README.md
> +Be cautious when running this command, as it will automatically fix any linting issues it can.
```suggestion
Be cautious when running this command, as it will automatically fix any formatting issues it can.
```

2024-10-11 21:02 UTC, stevector approved these changes

2024-10-11 21:02 UTC, merged